### ISSUE TITLE
Better script injection

### ISSUE THREAD

**Issue by paales** [AOEpeople/Aoe_TemplateHints#30]
Replace the following line:
https://github.com/AOEpeople/Aoe_TemplateHints/blob/master/app/code/community/Aoe/TemplateHints/Model/Observer.php#L95

```PHP
if ($this->init && strpos(get_class($block), "Mage_Persistent") === false) {
```

```PHP
if ($this->init && !Mage::getStoreConfigFlag('advanced/modules_disable_output/' . $block->getModuleName()) && $block->getNameInLayout()) {
```

**Comment by fbrnc** [comment]
That's a very good suggestion and feels a lot less like a hack than my solution :)

Would you mind creating a pull request?

**Comment by paales** [comment]
See #30
