### ISSUE TITLE
uncaught exception: Opentip requires the Prototype JavaScript framework >= 1.6.0

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_TemplateHints#32]
Looks like there's a situation where the javascript snippet is included before prototype is included.

**Comment by TKlement** [comment]
The problem still exists in 2020.

Suggestion that works:
app/code/community/Aoe/TemplateHints/Model/Renderer/Opentip.php:30
$wrappedHtml .= '<script type="text/javascript" src="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'prototype/prototype.js' . '"></script>';

Add prototype.js at first and the popup comes back and there is no error in the console.
