### ISSUE TITLE
Feature Request: Add linebreaks between END and START

### ISSUE THREAD

**Issue by winkelsdorf** [AOEpeople/Aoe_TemplateHints#33]
As mentioned in #25 I would like to suggest to add line-breaks after each [END] block and before a new [START] to make it easier to read the comments.

In the screenshot it's easy to miss [START: 63]:
![screen shot 2015-04-28 at 13 42 27](https://cloud.githubusercontent.com/assets/1413291/7368900/232b3c44-edad-11e4-89cc-7f4a7dabe713.png)

**Comment by joh-klein** [comment]
Could you please check, if this fixes it for you?

**Comment by winkelsdorf** [comment]
Gives

```code
Parse error: syntax error, unexpected '.' in /Users/winkelsdorf/sites/magento191.dev/app/code/community/Aoe/TemplateHints/Model/Renderer/Comment.php on line 31
```
Need to remove either the last point in 31 or 1st in 32.

Tested with fixed dot, looks way better :+1: 

Just the nested blocks are created like this
```code
 --><!-- [START: 20] catalog.topnav
```

But that's ok for me. The main issue was missing some START/END blocks, that's solved now.

**Comment by joh-klein** [comment]
Argh, sorry. Stupid mistake :) Try it like this, please.

**Comment by winkelsdorf** [comment]
Nevermind, In my own repo I made a mess yesterday too, due to too early commits and small typos 😂

Looks way better! Just after the start block, right before the content (see bottom of the screenshot) needs one more linebreak probably? But we are both very pedantic about 😆

In line 29 of your code:
```code
   '<!-- [START: %1$s] %4$s'."\n".'%5$s -->'.  "\n".
```
![screen shot 2015-04-29 at 15 44 25](https://cloud.githubusercontent.com/assets/1413291/7392221/c1e95634-ee86-11e4-9f52-a36b0129239a.png)

**Comment by joh-klein** [comment]
How we doing now? I added another linebreak before the [END] too (just for good measure)

**Comment by winkelsdorf** [comment]
Just tested, works perfectly fine. Thank you 👍

Hopefully this patch makes it into the master repo :)

**Comment by fbrnc** [comment]
Merged into master. Thank you for contributing and testing this!

**Comment by winkelsdorf** [comment]
You're welcome, Thank you both too!
